variables:
  Environment: 'Test' 
  AdoEnvironment: 'test-data'

  # GHUB lz variables (the factory varialbe name is pointless here, its in services folder)
  SubscriptionIdGHUB: "05d99ae7-a80c-47ea-8867-7ec5c1dc34a6"
  ResourceGroupNameGHUB: "lz-ghub-${{ lower(variables.Environment) }}-uks-rg-01"
  AzureDataFactoryPipelinesArmTemplateParametersDataAdf01: "Services/DataAnalytics/ARMTemplateParametersForFactory01${{ variables.Environment }}.json" #this file doesn't exist for dev

  # Arm template parameter files
  AzureKeyVaultArmTemplateParametersData: "ArmTemplates/Keyvault/Parameters/${{ upper(variables.Environment) }}/AzureKeyVault.Data.parameters.json"
  AzureSqlServerParametersData: "ArmTemplates/AzureSQL/Parameters/${{ upper(variables.Environment) }}/AzureSQL.Data.parameters.json"
  AzureDataFactoryParametersData: "ArmTemplates/DataFactory/Parameters/${{ upper(variables.Environment) }}/AzureDataFactory.parameters.json"
  AzureLogAnalyticsParameters: "ArmTemplates/LogAnalytics/Parameters/${{ upper(variables.Environment) }}/LogAnalytics.parameters.json"

 
  # DATransactions vars
  SQLBuildSourceFolder_dbLida: "SQL DBs/DatabaseLIDA"
  DADatabaseName: "DATransactions"

  # dafac source database vars
  SQLBuildSourceFolder_dbfacStuffSource: "SQL DBs/dafacstuffuks"
  DatabaseName_facstuff_source: "dba-fac-stf-source"

  # dafac target database vars
  SQLBuildSourceFolder_dbfacStuffTarget: "SQL DBs/dafacstuffuks-target"
  DatabaseName_facstuff_target: "dba-facstuff-target"

